name: Tests

on:
    workflow_dispatch: # Only enable manual runs for now

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # Define the Go versions to test against
                go-version: [ "1.19", "1.20", "1.21", "1.22", "1.23" ]

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4

            -   name: Set up Go ${{ matrix.go-version }}
                uses: actions/setup-go@v5
                with:
                    go-version: ${{ matrix.go-version }}

            # Install dependencies and run tests
            -   name: Install Dependencies
                run: |
                    go mod tidy
                    go mod download
                    sudo apt-get install -y make
                continue-on-error: false

            -   name: Run Tests
                run: |
                    make test
                continue-on-error: false
